import type { Creator, Restaurant, Mention, Source } from './types'

export const MARK_WIENS: Creator = {
  slug: 'mark-wiens',
  name: 'Mark Wiens',
  platform: 'youtube',
  avatarUrl: 'https://yt3.googleusercontent.com/ytc/AIdro_kZ4VXyN6kuKZb9NUVRjGM2HVOOXLY9hjjvc4FxzxQ8tw=s176-c-k-c0x00ffffff-no-rj',
  url: 'https://www.youtube.com/@MarkWiens',
  videoCount: 1,
  restaurantCount: 16,
}

export const BEST_EVER: Creator = {
  slug: 'best-ever-food-review-show',
  name: 'Best Ever Food Review Show',
  platform: 'youtube',
  avatarUrl: 'https://yt3.googleusercontent.com/ytc/AIdro_kPlaceholder1=s176-c-k',
  url: 'https://www.youtube.com/@BestEverFoodReviewShow',
  videoCount: 0,
  restaurantCount: 0,
}

export const STRICTLY_DUMPLING: Creator = {
  slug: 'strictly-dumpling',
  name: 'Strictly Dumpling',
  platform: 'youtube',
  url: 'https://www.youtube.com/@StrictlyDumpling',
  videoCount: 0,
  restaurantCount: 0,
}

export const CREATORS: Creator[] = [MARK_WIENS, BEST_EVER, STRICTLY_DUMPLING]

const MARK_HK_DOC: Source = {
  kind: 'youtube',
  url: 'https://www.youtube.com/watch?v=HWMga1ULQEU',
  title: 'Best HONG KONG Street Food!! 19 Meals - Ultimate Hong Kong Food Tour [Full Documentary]',
  thumbnailUrl: 'https://i.ytimg.com/vi/HWMga1ULQEU/maxresdefault.jpg',
  publishedAt: '2024-07-20',
  creator: MARK_WIENS,
}

// 18 Mark Wiens HK pins extracted from HWMga1ULQEU transcript.
// Coordinates are approximate (representative of the neighbourhood).
type RestaurantSeed = Omit<Restaurant, 'mentionCount' | 'topCreators'> & {
  mention: Omit<Mention, 'id' | 'restaurantId' | 'createdAt'>
}

const HK_SEEDS: RestaurantSeed[] = [
  {
    id: 'r-lung-king-heen',
    name: 'Lung King Heen',
    nameLocal: '龍景軒',
    city: 'Hong Kong',
    country: 'HK',
    lat: 22.2855,
    lng: 114.1577,
    cuisine: 'Cantonese · Dim Sum',
    priceLevel: 4,
    mention: {
      source: MARK_HK_DOC,
      dish: 'Abalone puff, har gow',
      timestampSec: 702,
      quote: 'Located at the Four Seasons Hotel overlooking Victoria Harbour is Lung King Heen. A highly regarded two-Michelin-star restaurant known for their elevated Cantonese cuisine.',
    },
  },
  {
    id: 'r-hing-kee-seafood',
    name: 'Hing Kee Seafood',
    nameLocal: '興記',
    city: 'Hong Kong',
    country: 'HK',
    lat: 22.2828,
    lng: 114.1832,
    cuisine: 'Seafood · Typhoon Shelter',
    priceLevel: 3,
    mention: {
      source: MARK_HK_DOC,
      dish: 'Original typhoon shelter crab with garlic & black bean',
      timestampSec: 1122,
      quote: 'Oh, welcome to Hing Kee Seafood. This is a restaurant with a lot of history. They\'re famous for their crabs, especially their typhoon shelter crab.',
    },
  },
  {
    id: 'r-sister-wah',
    name: 'Sister Wah',
    nameLocal: '華姐清湯腩',
    city: 'Hong Kong',
    country: 'HK',
    lat: 22.2828,
    lng: 114.1923,
    cuisine: 'Beef Brisket Noodles',
    priceLevel: 1,
    mention: {
      source: MARK_HK_DOC,
      dish: 'Beef brisket with rice noodles + brisket curry',
      timestampSec: 1634,
      quote: 'Sister Wah, they\'ve won almost every food award you can imagine, Michelin Guide, local Hong Kong awards.',
    },
  },
  {
    id: 'r-kam-wah',
    name: 'Kam Wah Cafe',
    nameLocal: '金華冰廳',
    city: 'Hong Kong',
    country: 'HK',
    lat: 22.3231,
    lng: 114.1697,
    cuisine: 'Cha Chaan Teng · Bakery',
    priceLevel: 1,
    mention: {
      source: MARK_HK_DOC,
      dish: 'Pineapple bun with butter (bo lo bao)',
      timestampSec: 1925,
      quote: 'Okay, we got it. The original, the legendary Kam Wah Bakery since 1973. The famous, the legendary Hong Kong pineapple bun.',
    },
  },
  {
    id: 'r-hing-kee-temple',
    name: 'Hing Kee (Temple Street)',
    nameLocal: '興記菜館',
    city: 'Hong Kong',
    country: 'HK',
    lat: 22.3093,
    lng: 114.1696,
    cuisine: 'Clay Pot Rice · Oyster Omelet',
    priceLevel: 2,
    mention: {
      source: MARK_HK_DOC,
      dish: 'Clay pot rice with chicken & sausage; auntie\'s deep-fried oyster omelet (44 years)',
      timestampSec: 2035,
      quote: 'So, welcome to Hing Kee. In this place, they\'re very famous for their Hong Kong style clay pot rice.',
    },
  },
  {
    id: 'r-oi-man-sang',
    name: 'Oi Man Sang',
    nameLocal: '愛文生',
    city: 'Hong Kong',
    country: 'HK',
    lat: 22.3306,
    lng: 114.1632,
    cuisine: 'Dai Pai Dong · Cantonese',
    priceLevel: 2,
    mention: {
      source: MARK_HK_DOC,
      dish: 'Razor clams in black bean sauce, fried potato & beef, fish head soup',
      timestampSec: 2523,
      quote: 'We\'re at Oi Man Sang, one of the most famous dai pai dongs IN HONG KONG. CAN YOU HEAR AND SMELL THE wok hei?',
    },
  },
  {
    id: 'r-ap-lei-chau',
    name: 'Ap Lei Chau Cooked Food Market (Cheng Cheng)',
    nameLocal: '鴨脷洲熟食市場',
    city: 'Hong Kong',
    country: 'HK',
    lat: 22.2415,
    lng: 114.1530,
    cuisine: 'Seafood · Wet Market Cook-Your-Catch',
    priceLevel: 2,
    mention: {
      source: MARK_HK_DOC,
      dish: 'Steamed grouper, threadfin w/ black bean, slipper lobster vermicelli, local prawns',
      timestampSec: 2826,
      quote: 'When you get your seafood downstairs at the seafood market, come to meet Cheng Cheng. She has the best recipes and the secret sauce is incredible.',
    },
  },
  {
    id: 'r-ssp-wonton-legendary',
    name: 'Sham Shui Po Wonton Noodle (legendary, 1956)',
    city: 'Hong Kong',
    country: 'HK',
    lat: 22.3306,
    lng: 114.1622,
    cuisine: 'Wonton Noodles',
    priceLevel: 1,
    mention: {
      source: MARK_HK_DOC,
      dish: 'Shrimp wonton soup + dry brisket noodles with shrimp roe',
      timestampSec: 3289,
      quote: 'This is a legendary restaurant dating back to 1956. It\'s three generations still in the family, and they are most famous for their wonton noodles and their homemade noodles.',
    },
  },
  {
    id: 'r-sampan-typhoon',
    name: 'Typhoon Shelter Sampan Dinner',
    city: 'Hong Kong',
    country: 'HK',
    lat: 22.2780,
    lng: 114.1880,
    cuisine: 'Seafood · Sampan Boat',
    priceLevel: 3,
    mention: {
      source: MARK_HK_DOC,
      dish: 'Garlic + black-bean typhoon shelter crab with fried noodles (eaten on the boat)',
      timestampSec: 3554,
      quote: 'We\'re actually going to get onto one of the original boats, a sampan, and we\'re going to enjoy another seafood meal in a different version of typhoon shelter crab in the typhoon shelter.',
    },
  },
  {
    id: 'r-sun-kwai-heung',
    name: 'Sun Kwai Heung',
    nameLocal: '新桂香燒臘',
    city: 'Hong Kong',
    country: 'HK',
    lat: 22.2641,
    lng: 114.2363,
    cuisine: 'Cantonese BBQ · Char Siu',
    priceLevel: 2,
    mention: {
      source: MARK_HK_DOC,
      dish: 'Maltose-glazed char siu (medium-fatty + fatty cuts)',
      timestampSec: 3804,
      quote: 'We are in Chai Wan at a place called Sun Kwai Heung and it is considered honestly the best char siu in Hong Kong and it just came out of the oven.',
    },
  },
  {
    id: 'r-wing-hop-lung',
    name: 'Wing Hop Lung',
    nameLocal: '永合隆飯店',
    city: 'Hong Kong',
    country: 'HK',
    lat: 22.3245,
    lng: 114.1683,
    cuisine: 'Charcoal-Roasted Suckling Pig',
    priceLevel: 3,
    mention: {
      source: MARK_HK_DOC,
      dish: 'Suckling pig + large charcoal-roasted pig',
      timestampSec: 4143,
      quote: 'We\'re at Wing Hop Lung and we\'re here to try roasted meats and the suckling pig.',
    },
  },
  {
    id: 'r-yat-lok',
    name: 'Yat Lok',
    nameLocal: '一樂燒鵝',
    city: 'Hong Kong',
    country: 'HK',
    lat: 22.2829,
    lng: 114.1547,
    cuisine: 'Roast Goose',
    priceLevel: 2,
    mention: {
      source: MARK_HK_DOC,
      dish: 'Whole roast goose, leg quarter on rice',
      timestampSec: 4433,
      quote: 'So, Yat Lok, famous for their roast goose, which is something that you absolutely have to eat when you come to Hong Kong. Three brothers, three generations.',
    },
  },
  {
    id: 'r-the-chairman',
    name: 'The Chairman',
    nameLocal: '大班樓',
    city: 'Hong Kong',
    country: 'HK',
    lat: 22.2823,
    lng: 114.1551,
    cuisine: 'Cantonese · Modern',
    priceLevel: 4,
    mention: {
      source: MARK_HK_DOC,
      dish: 'Steamed flower crab over aged-Shaoxing chicken-fat rice noodles; mei cai kou yuk claypot',
      timestampSec: 5154,
      quote: 'Welcome to The Chairman. The Chairman was started 14 years ago and... one of the highest regarded local Hong Kong restaurants serving traditional yet innovative.',
    },
  },
  {
    id: 'r-wing-kee',
    name: 'Wing Kee',
    nameLocal: '榮記',
    city: 'Hong Kong',
    country: 'HK',
    lat: 22.2785,
    lng: 114.1830,
    cuisine: 'Dai Pai Dong · Cantonese',
    priceLevel: 2,
    mention: {
      source: MARK_HK_DOC,
      dish: 'Sweet and sour pork, oil-basted fried chicken',
      timestampSec: 6136,
      quote: 'This restaurant is called Wing Kee and it is a legendary like food court style dai pai dong style market restaurant. Extremely popular in the neighborhood in Causeway Bay.',
    },
  },
  {
    id: 'r-dim-sum-hsbc',
    name: 'Old-school Dim Sum House (above HSBC)',
    city: 'Hong Kong',
    country: 'HK',
    lat: 22.2802,
    lng: 114.1612,
    cuisine: 'Dim Sum · Trolley',
    priceLevel: 1,
    mention: {
      source: MARK_HK_DOC,
      dish: 'Har gow, beef balls, bean curd roll, sticky rice in lotus leaf',
      timestampSec: 262,
      quote: 'I think it\'s right on that second level where those windows are, right above the HSBC bank.',
    },
  },
  {
    id: 'r-tomato-cafe',
    name: 'Macaroni Tomato Cafe (47 years, unnamed)',
    city: 'Hong Kong',
    country: 'HK',
    lat: 22.2818,
    lng: 114.1545,
    cuisine: 'Cha Chaan Teng',
    priceLevel: 1,
    mention: {
      source: MARK_HK_DOC,
      dish: 'Macaroni in tomato broth with beef + egg; lemon-sugar bun',
      timestampSec: 1462,
      quote: 'She actually used to sell hot dogs with tomato on it... she made the recipe and she\'s been doing this for 47 years now and she\'s 62 this year.',
    },
  },
  {
    id: 'r-prince-edward-streetfood',
    name: 'Prince Edward Street Food Walk',
    city: 'Hong Kong',
    country: 'HK',
    lat: 22.3245,
    lng: 114.1683,
    cuisine: 'Street Food · Stinky Tofu · Fish Balls',
    priceLevel: 1,
    mention: {
      source: MARK_HK_DOC,
      dish: 'Stinky tofu, fried pig intestines, curry fish balls',
      timestampSec: 1786,
      quote: 'In the afternoon, we headed to Prince Edward in Kowloon for a quick tour to eat extremely iconic Hong Kong street foods. Most of them on sticks.',
    },
  },
  {
    id: 'r-day5-neighborhood-dimsum',
    name: 'Neighborhood Dim Sum (Day 5, all-day, unnamed)',
    city: 'Hong Kong',
    country: 'HK',
    lat: 22.2855,
    lng: 114.1500,
    cuisine: 'Dim Sum',
    priceLevel: 1,
    mention: {
      source: MARK_HK_DOC,
      dish: 'Har gow, bean curd roll, sponge cake',
      timestampSec: 4845,
      quote: 'It\'s such a great neighborhood spot. This place is famous for making their own dim sum upstairs and then steaming it and serving it.',
    },
  },
]

const now = new Date().toISOString()
let mid = 1

export const MOCK_RESTAURANTS: Restaurant[] = HK_SEEDS.map((seed) => ({
  id: seed.id,
  name: seed.name,
  nameLocal: seed.nameLocal,
  city: seed.city,
  country: seed.country,
  lat: seed.lat,
  lng: seed.lng,
  cuisine: seed.cuisine,
  priceLevel: seed.priceLevel,
  placesId: seed.placesId,
  mentionCount: 1,
  topCreators: [MARK_WIENS],
}))

export const MOCK_MENTIONS: Mention[] = HK_SEEDS.map((seed) => ({
  id: `m-${mid++}`,
  restaurantId: seed.id,
  source: seed.mention.source,
  dish: seed.mention.dish,
  quote: seed.mention.quote,
  timestampSec: seed.mention.timestampSec,
  anchor: seed.mention.anchor,
  createdAt: now,
}))

// Update creator restaurant count from actual data
MARK_WIENS.restaurantCount = MOCK_RESTAURANTS.length
MARK_WIENS.videoCount = 1
